using System;

namespace ImGuiSharp.Rendering;

/// <summary>
/// Describes a rendering pipeline capable of translating ImGui draw data into GPU commands.
/// </summary>
public interface IRenderPipeline : IDisposable
{
    /// <summary>
    /// Prepares the pipeline for a new frame, ensuring underlying resources are ready.
    /// </summary>
    void BeginFrame();

    /// <summary>
    /// Submits draw data generated by the core library to the GPU.
    /// </summary>
    /// <param name="drawData">The draw data instance describing command lists to render.</param>
    void Render(ImGuiDrawData drawData);

    /// <summary>
    /// Completes the frame, presenting results or flushing commands as required.
    /// </summary>
    void EndFrame();
}
